//Success

//Error
export const ERROR_CREATE_CATEGORY = 'ERROR_CREATE_CATEGORY';
export const ERROR_GET_ALL_CATEGORIES = 'ERROR_GET_ALL_CATEGORIES';
export const ERROR_CATEGORY_NOT_FOUND = 'ERROR_CATEGORY_NOT_FOUND';
