//Error
export const ERROR_CREATE_COMMENT = 'ERROR_CREATE_COMMENT';
export const ERROR_COMMENT_NOT_FOUND = 'ERROR_COMMENT_NOT_FOUND';
export const ERROR_GET_COMMENTS = 'ERROR_GET_COMMENTS';
export const ERROR_REACTION_COMMENTS = 'ERROR_REACTION_COMMENTS';
