//Success

//Error
export const ERROR_CREATE_POST = 'ERROR_CREATE_POST';
export const ERROR_GET_POST = 'ERROR_GET_POST';
export const ERROR_GET_TOP_STORIES = 'ERROR_GET_TOP_STORIES';
export const ERROR_GET_LATEST_POSTS_ALL_CATEGORIES =
    'ERROR_GET_LATEST_POSTS_ALL_CATEGORIES';
export const ERROR_GET_RELATED_POSTS = 'ERROR_GET_RELATED_POSTS';
export const ERROR_POST_NOT_FOUND = 'ERROR_POST_NOT_FOUND';
export const ERROR_GET_LATEST_POST = 'ERROR_GET_LATEST_POST';
export const ERROR_GET_POSTS_BY_CATEGORY = 'ERROR_GET_POSTS_BY_CATEGORY';
