//Success

//Error
export const ERROR_GET_USER_INFO = 'ERROR_GET_USER_INFO';
export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const ERROR_EMAIL_NOT_FOUND = 'ERROR_EMAIL_NOT_FOUND';
export const ERROR_PASSWORD_NOT_MATCH = 'ERROR_PASSWORD_NOT_MATCH';
export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const ERROR_EMAIL_HAS_BEEN_USED = 'ERROR_EMAIL_HAS_BEEN_USED';
